### ISSUE TITLE
HR | Document download not working on old documents

### ISSUE THREAD

**Issue by alaaOs** [alqmte/prohealth#57]
#13 
In old documents images were saved as dataURLs, and this case wasn't handled in the download functionality.

**Comment by alqmte** [comment]
http://prohealth.io/agents/WdubhNjPQRYSLLGdo/edit

**Comment by alqmte** [comment]
[52.88.106.209]Exception while invoking method 'getAllDataUris' Error: Invalid protocol: null
    at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:446:16)
    at Function.getSync (packages/meteor.js:213:24)
[52.88.106.209]    at packages/prohealth:hr-documents/server/downloadDocs.js:66:40
[52.88.106.209]    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore.js:139:11)
[52.88.106.209]    at packages/prohealth:hr-documents/server/downloadDocs.js:64:15
    at Array.forEach (native)
[52.88.106.209]    at Function._.each._.forEach (packages/underscore.js:139:11)
    at [object Object].getDataUri (packages/prohealth:hr-documents/server/downloadDocs.js:52:9)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
[52.88.106.209]    - - - - -
    at Request.self._buildRequest (/bundle/bundle/programs/server/npm/node_modules/meteor/froatsnook_request/node_modules/request/request.js:355:53)
[52.88.106.209]    at Request.init (/bundle/bundle/programs/server/npm/node_modules/meteor/froatsnook_request/node_modules/request/request.js:533:10)
    at new Request (/bundle/bundle/programs/server/npm/node_modules/meteor/froatsnook_request/node_modules/request/request.js:99:8)
[52.88.106.209]    at request (/bundle/bundle/programs/server/npm/node_modules/meteor/froatsnook_request/node_modules/request/index.js:54:11)
    at Function.requestAsync (packages/froatsnook_request.js:44:2)
    at Function.getSync (packages/meteor.js:212:23)
    at packages/prohealth:hr-documents/server/downloadDocs.js:66:40
[52.88.106.209]    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore.js:139:11)
[52.88.106.209]    at packages/prohealth:hr-documents/server/downloadDocs.js:64:15
document_Type_id:  nodoctype
